### PR TITLE
Version 0.2.4

### PR DESCRIPTION
**Pull request by LexiBigCheese**

### CODE REVIEW

**Comment by luisvt** [comment]
Sorry I had forgotten to release the new version

**Comment by LexiBigCheese** [comment]
Ok mate, i just need you to upload to pub

Thanks!

Also this pulling thing is pretty cool!

**Comment by luisvt** [comment]
I already did it: https://pub.dartlang.org/packages/built_mirrors

**Comment by LexiBigCheese** [comment]
Cool, man.

**Pull request closed without merging**
